modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="lots_of_steves" #mandatory
version="0.17" #mandatory
displayName="Lot's Of Steves" #mandatory
credits="Thanks to my team - Kathairis Dev Team" #optional
authors="Krevik" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Simple mod, that adds automatic workes"